# Generated by Django 3.0.1 on 2019-12-25 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogMessage',
            new_name='Message',
        ),
    ]
