# Generated by Django 3.0.1 on 2019-12-25 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0002_auto_20191225_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='text',
        ),
    ]
